# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Service
metadata:
    name: dlp-ext-proc-svc
    labels:
        app: dlp-ext-proc
        app.kubernetes.io/name: dlp-ext-proc
        app.kubernetes.io/component: service
    annotations:
        cloud.google.com/neg: '{"exposed_ports": {"443":{"name": "dlp-ext-proc-neg"}}}'
spec:
    type: ClusterIP
    selector:
        app: dlp-ext-proc
    ports:
        - name: grpc
          port: 443
          targetPort: 8443
          protocol: TCP
          appProtocol: HTTP2
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
    name: dlp-ext-proc-health
spec:
    targetRef:
        group: ""
        kind: Service
        name: dlp-ext-proc-svc
    default:
        config:
            type: GRPC
            grpcHealthCheck:
                port: 8080
        checkIntervalSec: 15
        timeoutSec: 10
        healthyThreshold: 2
        unhealthyThreshold: 3
        logConfig:
            enabled: true
