# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Service
metadata:
    name: corporate-email-svc
    labels:
        app: corporate-email
        app.kubernetes.io/name: corporate-email
        app.kubernetes.io/component: service
    annotations:
        cloud.google.com/neg: '{"exposed_ports": {"8080":{"name": "corporate-email-neg"}}}'
spec:
    type: ClusterIP
    selector:
        app: corporate-email
    ports:
        - name: http
          port: 8080
          targetPort: 8080
          protocol: TCP
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
    name: corporate-email-health
spec:
    targetRef:
        group: ""
        kind: Service
        name: corporate-email-svc
    default:
        config:
            type: HTTP
            httpHealthCheck:
                port: 8080
                requestPath: /health
        checkIntervalSec: 15
        timeoutSec: 10
        healthyThreshold: 2
        unhealthyThreshold: 3
        logConfig:
            enabled: true
