formatter: markdown table

output:
  file: README.md
  mode: inject

settings:
  anchor: true
  color: true
  default: true
  description: true
  html: true
  indent: 2
  required: true
  sensitive: true
  type: true
