# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: cloud.google.com/v1
kind: ComputeClass
metadata:
    name: dws-flex-h100
spec:
    priorities:
        - machineType: a3-highgpu-1g
          gpu:
              type: nvidia-h100-80gb
              count: 1
              driverVersion: latest
          spot: true
        - machineType: a3-highgpu-1g
          gpu:
              type: nvidia-h100-80gb
              count: 1
              driverVersion: latest
          maxRunDurationSeconds: 72000
          flexStart:
              enabled: true
              nodeRecycling:
                  leadTimeSeconds: 3600
    nodePoolAutoCreation:
        enabled: true
---
apiVersion: cloud.google.com/v1
kind: ComputeClass
metadata:
    name: dws-flex-a100
spec:
    priorities:
        - machineType: a2-ultragpu-1g
          gpu:
              type: nvidia-a100-80gb
              count: 1
              driverVersion: latest
          spot: true
        - machineType: a2-ultragpu-1g
          gpu:
              type: nvidia-a100-80gb
              count: 1
              driverVersion: latest
          maxRunDurationSeconds: 72000
          flexStart:
              enabled: true
              nodeRecycling:
                  leadTimeSeconds: 3600
        # If we can't get 80GB A100's try 40GB A100's
        - machineType: a2-highgpu-1g
          gpu:
              type: nvidia-tesla-a100
              count: 1
              driverVersion: latest
          spot: true
        - machineType: a2-highgpu-1g
          gpu:
              type: nvidia-tesla-a100
              count: 1
              driverVersion: latest
          maxRunDurationSeconds: 72000
          flexStart:
              enabled: true
              nodeRecycling:
                  leadTimeSeconds: 3600
    nodePoolAutoCreation:
        enabled: true
